### ISSUE TITLE
Several coding errors prevent building

### ISSUE THREAD

**Issue by ghost** [kasworld/go-sdlgui#1]
The package won't compile due to self inconsistencies:

basecontrol.go, line 52:
 52    t := c.Win.Rend.CreateTextureFromSurface(c.Suf)

basecontrol.go line 154:
154 func (renderer _Renderer) CreateTextureFromSurface(surface *Surface) (_Texture, error) {

The function definition returns two values; in the same file, the call expects one.  This results in compile errors:
./basecontrol.go:52: multiple-value c.Win.Rend.CreateTextureFromSurface() in single-value context

There are 8 such errors in the current commit.  It looks like a refactor got committed before it was complete, or compiled.
# github.com/kasworld/go-sdlgui

./basecontrol.go:52: multiple-value c.Win.Rend.CreateTextureFromSurface() in single-value context
./basecontrol.go:127: multiple-value sdl.CreateSoftwareRenderer() in single-value context
./basecontrol.go:154: multiple-value c.Rend.CreateTextureFromSurface() in single-value context
./font.go:71: multiple-value rend.CreateTextureFromSurface() in single-value context
./util.go:37: multiple-value img.Load() in single-value context
./window.go:110: multiple-value sdl.CreateWindow() in single-value context
./window.go:113: multiple-value sdl.CreateWindow() in single-value context
./window.go:119: multiple-value sdl.CreateRenderer() in single-value context

--- SER

**Comment by kasworld** [comment]
build failure is from changed api It use 
( https://github.com/veandco/go-sdl2) 
update and changed to use own forked version
